version: 2

# note: we split each app out individually to force dependabot to open individual, separate PRs for each apps
# so that app changes are decoupled from one another
# yaml anchors and aliases are not support in dependabot -- so lot's of repetition here!
updates:
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/adapt-essentials-asset-fields'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/bynder'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/ceros'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/cloudinary'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/cloudinary2'
    ignore:
      - dependency-name: '@contentful/app-sdk'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/flexfields'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/imageHotspotCreator'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/shopify'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/surfer'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/transifex'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/uploadcare'
  - package-ecosystem: npm
    schedule:
      interval: daily
      time: '03:00'
      timezone: UTC
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    directory: '/apps/voucherify'
