name: CI

on:
  push:
    branches: ['main', 'production']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, Test, Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DEFINITIONS_ORG_ID: ${{ secrets.DEFINITIONS_ORG_ID }}
      CONTENTFUL_CMA_TOKEN: ${{ secrets.CONTENTFUL_CMA_TOKEN }}
      TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}
      TEST_CMA_TOKEN: ${{ secrets.TEST_CMA_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Print commit SHA
        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Print main SHA
        run: echo ${{ github.event.pull_request.base.sha }}
      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: /tmp/github-cache
          key: ${{ runner.os }}-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.event.pull_request.base.sha }}
      - name: Root dependencies
        run: npm install
      - name: App dependencies
        run: npm run install-apps
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Deploy Staging
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run deploy:staging
      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: npm run deploy
