name: CI

on:
  push:
    branches: ['main', 'production']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, Test, Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DEFINITIONS_ORG_ID: ${{ secrets.DEFINITIONS_ORG_ID }}
      CONTENTFUL_CMA_TOKEN: ${{ secrets.CONTENTFUL_CMA_TOKEN }}
      TEST_ORG_ID: ${{ secrets.TEST_ORG_ID }}
      TEST_CMA_TOKEN: ${{ secrets.TEST_CMA_TOKEN }}
      HaT_ORG_ID: ${{ secrets.HaT_ORG_ID }}
      HaT_TOKEN: ${{ secrets.HaT_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install contentful
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/production' }}
        run: brew install contentful
      - name: Build
        run: npm run build -- --filter=...[HEAD^1]
      - name: Test
        run: npm run test -- --filter=...[HEAD^1]
      - name: Deploy Test Env
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/production' }}
        run: contentful space create -y --mt ${{ secrets.HaT_TOKEN }} --org ${{ secrets.HaT_ORG_ID }} -n ${{ github.ref_name }}
      - name: Deploy Staging
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run deploy:staging -- --filter=...[HEAD^1]
      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: npm run deploy -- --filter=...[HEAD^1]
