---
name: 'New App Review'

"on":
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'main'

jobs:
  main:
    name: New App Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
          # Ensure the workflow can access the forked repository's contents
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Compile TypeScript
        # compilation is necessary because github-script does not support ts
        # https://github.com/actions/github-script/issues/294
        run: npx tsc --project .github/workflows/tsconfig.json
      - uses: actions/github-script@v7
        with:
          script: |
            const { review } = require(
              './.github/workflows/dist/new-app-review'
            );
            const { chdir, cwd } = require('node:process');
            chdir(cwd());
            await review({
              github,
              ctx: context,
              ghCore: core
            });
